### ISSUE TITLE
image afolarin/cron-apache-php:latest not found

### ISSUE THREAD

**Issue by scloo** [KHP-Informatics/redcap-docker#1]
Tried to build according to your instructions. However building the webapp image throws an error. The trace shows:

$ docker build --tag="afolarin/redcap:webapp" .
Sending build context to Docker daemon 27.21 MB
Sending build context to Docker daemon 
Step 0 : FROM afolarin/cron-apache-php
Pulling repository afolarin/cron-apache-php
INFO[0035] Error: image afolarin/cron-apache-php:latest not found 

Any advice?

**Comment by afolarin** [comment]
Hi @scloo my apologies for the delay getting to this issue.

I'd forgotten to push the afolairn/cron-apache-php Dockerfile (see the web-base folder). 
I've corrected the instructions and tested this is working properly.

**Comment by scloo** [comment]
Thanks for fixing the issue. Yes it is now working. Although I have a question that maybe you can help me with when using redcap docker.
I have installed the redcap docker on a Mac. And the server is up and running. However I am not able to set up my REDCap mobile app to connect to the redcap docker server.
Generally I just need to point to the PC ip address to access the Redcap server. EG http://IP:PORT/redcap
But due to the fact that Docker can only run on Mac using Boot2Docker, which is itself a VM and could be accessed via its boot2docker IP. EG 192.168.59.105. This ip is only available to the PC but not available to the tablet since it is on a different subnet. I can access via the PC IP since it is on the same subnet as the tablet. But the docker is on a different vboxnet.  Hence when trying to set up the mobile project on the device, it would not recognize the QR code nor the initialization code.
Just wondering if you have encountered such a problem.

Thanks
Steve

**Comment by ghost** [comment]
Did  you mean you want to be able to access the port, which is open on the boot2docker VM from outside the host machine, as though it were running on a port on the host machine? If so, maybe have a look at the Port Forwarding section of https://github.com/boot2docker/boot2docker/blob/master/doc/WORKAROUNDS.md?

Any help?
Cass.

On 2 Jul 2015, at 22:55, scloo <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for fixing the issue. Yes it is now working. Although I have a question that maybe you can help me with when using redcap docker.
I have installed the redcap docker on a Mac. And the server is up and running. However I am not able to set up my REDCap mobile app to connect to the redcap docker server.
Generally I just need to point to the PC ip address to access the Redcap server. EG http://IP:PORT/redcap
But due to the fact that Docker can only run on Mac using Boot2Docker, which is itself a VM and could be accessed via its boot2docker IP. EG 192.168.59.105. This ip is only available to the PC but not available to the tablet since it is on a different subnet. I can access via the PC IP since it is on the same subnet as the tablet. But the docker is on a different vboxnet. Hence when trying to set up the mobile project on the device, it would not recognize the QR code nor the initialization code.
Just wondering if you have encountered such a problem.

Thanks
Steve

**Comment by afolarin** [comment]
@scloo as Cas mentioned. But in practice I just use a micro EC2 instance for testing non-local access

**Comment by scloo** [comment]
Thanks Cass for your tip. The port forwarding is helpful. However it still did not solve the problem that I'm encountering. Basically I'm trying to set up my Redcap mobile app on my tablet which is on the same wireless network as my  mac laptop running Redcap server. When I go into the Redcap Mobile App page on the server, to scan the QR code (or generate the initialization code) with my tablet, it couldn't find the server. Thanks for your help just the same. I think I'll try set up a test server in the cloud instead.

**Comment by afolarin** [comment]
​​
Incidentally the RC app was not working for me until a recent update -- it
was failing at the step you mention

​https://groups.google.com/forum/#!topic/project-redcap/qv8MkgqA5No just in
case you are experiencing this too

​

**Comment by scloo** [comment]
Thanks for highlighting the update. I checked my version and it is the latest version.
I am not able to view the link you gave as I am not a member of this group. And there is no link for me to join the group either.
